
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezwoozlwsokkkbkeolmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6d29vemx3c29ra2tia2VvbG11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxODc4MjIsImV4cCI6MjA2Mjc2MzgyMn0.YWVJHeTHXc03CDS4MY7bd8kzQZXGYgJMy5xY69LbGoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  },
  global: {
    headers: {
      'x-app-name': 'TransactionAgent'
    }
  }
});
